### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by icemac** [zestsoftware/zest.pocompile#1]
Are there any plans to support Python 3?

zopefoundation/z3c.form seems to need it to create eggs/wheels containing *.mo files.

**Comment by mauritsvanrees** [comment]
I have checked `zest.pocompile` for Python 3 compatibility, and have released version 1.5.0. But it really needed no changes. I have released a [test package](https://pypi.org/project/mauritstestpackage2/1.25.0/#files) with it that correctly includes a `.mo` file.
It helps that https://pypi.org/project/python-gettext/ is Python 3 compatible.
